/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;
import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;

import java.io.*;
import java.util.LinkedList;

public class Compiler {
    public static void main(String[] args) {
        if (args.length < 1) {
            System.out.println("No input file");
            return;
        }
        boolean showLexer = args[0].equals("-lexer");
        if (showLexer && args.length < 2) {
            System.out.println("No input file");
            return;
        }
        String inputPath = args[(showLexer ? 1 : 0)];
        Lexer lex = lexerGetter(inputPath, showLexer);
    }

    public static Lexer lexerGetter(String inputPath,boolean showLexer) {
            System.out.printf("Input file: %s\n", inputPath);
            System.out.printf("Lexer: %s\n", showLexer ? "true" : "false");
            LinkedList<Symbol> symbolList = new LinkedList<Symbol>();
            try {
                File myObj = new File(inputPath);
                Reader reader = new FileReader(myObj);
                Lexer lex = new Lexer(reader);
                if (showLexer) {
                    while (true) {
                        Symbol s = lex.getNextSymbol();
                        if (s == null) {
                            break;
                        }
                        symbolList.add(s);
                    }
                    System.out.println(symbolList);
                }
                return lex;
            } catch (FileNotFoundException e) {
                System.out.println("An error occurred. File not found.");
                e.printStackTrace();
            }  catch (Exception e) {
                throw new RuntimeException(e);
            }
            return null;
    }
}
